import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHmac} from 'node:crypto';
import ts from 'typescript';
process.env.SUPABASE_URL='https://database.invalid';
process.env.SUPABASE_SERVICE_KEY='synthetic-test-secret';
const src=await readFile(new URL('../src/app/api/eventus/route.ts',import.meta.url),'utf8');
const {POST,GET}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'));
const token=(scope,code='AAA',guestId='1')=>{const p=Buffer.from(JSON.stringify({scope,code,guestId,exp:Math.floor(Date.now()/1000)+3600,nonce:'test'})).toString('base64url');return 'ev1.'+p+'.'+createHmac('sha256','synthetic-test-secret').update('eventus-v1.'+p).digest('base64url');};
let calls=[];
globalThis.fetch=async(url,opts)=>{calls.push({url:String(url),body:opts.body&&JSON.parse(opts.body)}); if(String(url).includes('eventus_events'))return Response.json([{code:'AAA'}]); if(String(url).includes('muro_config'))return Response.json([{enabled:true,gallery_token:'gallery-only'}]); return Response.json({guest:{id:1},alreadyArrived:false});};
const post=(body,admin=false)=>POST(new Request('https://example.test/api/eventus',{method:'POST',headers:{'content-type':'application/json',...(admin?{cookie:'eventus_admin='+token('admin')}:{})},body:JSON.stringify(body)}));
assert.equal((await post({op:'guest-checkin',code:'AAA',accessToken:token('event'),guestId:1})).status,403);
assert.equal((await post({op:'guest-checkin',code:'AAA',guestToken:token('guest','BBB')},true)).status,401);
assert.equal((await post({op:'guest-checkin',code:'AAA',guestToken:token('guest')+'broken'},true)).status,401);
assert.equal((await post({op:'guest-checkin',code:'AAA',guestToken:token('guest')},true)).status,200);
assert.equal(calls.at(-1).body.p_event_code,'AAA'); assert.equal(calls.at(-1).body.p_data.guestId,'1');
assert.equal((await post({op:'guest-seat',accessToken:token('event'),code:'BBB',guestId:1,mesa:1,expectedVersion:1})).status,403);
assert.equal((await post({op:'program-save',accessToken:token('event'),name:'A',time:'99:00',dur:20,note:'',responsible:'',status:'pending'})).status,400);
assert.equal((await post({op:'db',table:'eventus_guests',method:'PATCH',query:'id=eq.1',body:{arrived:true},accessToken:token('event')})).status,400);
assert.equal((await post({op:'db',table:'eventus_program',method:'DELETE',query:'id=eq.1',accessToken:token('event')})).status,400);
const gallery=await (await post({op:'gallery-get',accessToken:token('event')})).json();
assert.equal(gallery.uploadUrl,'https://muro-villaverde.vercel.app/e/AAA'); assert.equal(gallery.galleryUrl,'https://muro-villaverde.vercel.app/galeria/gallery-only');
assert.ok(calls.find(c=>c.url.includes('muro_config')).url.includes('event_code=eq.AAA')); assert.ok(!calls.find(c=>c.url.includes('muro_config')).url.includes('screen_token'));
console.log('Eventus API: admin-only reception, altered/cross-event tokens, scope, dedicated mutations and gallery projection passed');
